/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    blogs: Blog;
    'internal-links': InternalLink;
    'seo-pages': SeoPage;
    'seo-images': SeoImage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'internal-links': InternalLinksSelect<false> | InternalLinksSelect<true>;
    'seo-pages': SeoPagesSelect<false> | SeoPagesSelect<true>;
    'seo-images': SeoImagesSelect<false> | SeoImagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Use external CDN URL instead of upload
   */
  externalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage blog posts with SEO optimization
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  /**
   * Main blog title (50-60 characters recommended)
   */
  title: string;
  /**
   * URL-friendly slug (auto-generated from title)
   */
  slug: string;
  /**
   * Brief summary (150-160 characters)
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Featured image (1200x630px recommended)
   */
  featuredImage?: (string | null) | Media;
  /**
   * FAQs for featured snippets
   */
  faq?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Override global SEO settings for this post
   */
  meta?: {
    /**
     * SEO title (leave blank to use post title)
     */
    title?: string | null;
    /**
     * Meta description (leave blank to use excerpt)
     */
    description?: string | null;
    /**
     * Target keywords (3-5 recommended)
     */
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Canonical URL (optional)
     */
    canonical?: string | null;
    /**
     * Social media image (uses featured image if blank)
     */
    ogImage?: (string | null) | Media;
    robotsIndex?: boolean | null;
    robotsFollow?: boolean | null;
  };
  publishedAt?: string | null;
  author?: (string | null) | User;
  categories?:
    | {
        category: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-calculated reading time (minutes)
   */
  readingTime?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Automated internal linking for SEO
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-links".
 */
export interface InternalLink {
  id: string;
  /**
   * Domain (multi-site)
   */
  site: string;
  /**
   * Keyword/phrase to link
   */
  keyword: string;
  /**
   * Target URL (e.g., /blogs/nextjs-guide)
   */
  target_url: string;
  /**
   * Tooltip (optional)
   */
  title?: string | null;
  /**
   * rel="nofollow"
   */
  nofollow?: boolean | null;
  /**
   * Higher = first (0-100)
   */
  priority?: number | null;
  /**
   * Max links per page (1-3 recommended)
   */
  max_links_per_page?: number | null;
  /**
   * Match type
   */
  match_type: 'word' | 'phrase' | 'regex';
  /**
   * Enable rule
   */
  isActive?: boolean | null;
  /**
   * Notes
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage SEO metadata for all website pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-pages".
 */
export interface SeoPage {
  id: string;
  /**
   * Domain name (for multi-site management)
   */
  site: string;
  /**
   * Page URL path (e.g., /, /about, /blogs, /blogs/my-post)
   */
  slug: string;
  /**
   * SEO title (50-60 characters recommended)
   */
  metaTitle?: string | null;
  /**
   * Meta description (150-160 characters recommended)
   */
  metaDescription?: string | null;
  /**
   * Target keywords for this page (5-10 recommended)
   */
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Canonical URL (prevents duplicate content issues)
   */
  canonical?: string | null;
  /**
   * How this page appears when shared on social media
   */
  openGraph?: {
    /**
     * Social media title (can differ from meta title)
     */
    ogTitle?: string | null;
    /**
     * Social media description
     */
    ogDescription?: string | null;
    /**
     * Social media image (1200x630px recommended)
     */
    ogImage?: (string | null) | Media;
  };
  /**
   * Control how search engines crawl and index this page
   */
  robots?: {
    /**
     * Allow search engines to index this page
     */
    index?: boolean | null;
    /**
     * Allow search engines to follow links on this page
     */
    follow?: boolean | null;
  };
  /**
   * Additional structured data for rich snippets (advanced)
   */
  schema_json?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Optimize images for SEO/social
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-images".
 */
export interface SeoImage {
  id: string;
  /**
   * Domain
   */
  site: string;
  /**
   * Page slug (e.g., /blogs/tech)
   */
  page_slug: string;
  /**
   * Upload image
   */
  image?: (string | null) | Media;
  /**
   * Direct URL (override)
   */
  image_url?: string | null;
  /**
   * Alt text (descriptive, keywords)
   */
  alt_text?: string | null;
  /**
   * Caption
   */
  caption?: string | null;
  /**
   * Keywords for image
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Purpose
   */
  imageType?: ('featured' | 'content' | 'og' | 'product' | 'other') | null;
  /**
   * Px sizes
   */
  dimensions?: {
    /**
     * Width
     */
    width?: number | null;
    /**
     * Height
     */
    height?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blogs';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'internal-links';
        value: string | InternalLink;
      } | null)
    | ({
        relationTo: 'seo-pages';
        value: string | SeoPage;
      } | null)
    | ({
        relationTo: 'seo-images';
        value: string | SeoImage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  externalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonical?: T;
        ogImage?: T;
        robotsIndex?: T;
        robotsFollow?: T;
      };
  publishedAt?: T;
  author?: T;
  categories?:
    | T
    | {
        category?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  readingTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-links_select".
 */
export interface InternalLinksSelect<T extends boolean = true> {
  site?: T;
  keyword?: T;
  target_url?: T;
  title?: T;
  nofollow?: T;
  priority?: T;
  max_links_per_page?: T;
  match_type?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-pages_select".
 */
export interface SeoPagesSelect<T extends boolean = true> {
  site?: T;
  slug?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  canonical?: T;
  openGraph?:
    | T
    | {
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  robots?:
    | T
    | {
        index?: T;
        follow?: T;
      };
  schema_json?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-images_select".
 */
export interface SeoImagesSelect<T extends boolean = true> {
  site?: T;
  page_slug?: T;
  image?: T;
  image_url?: T;
  alt_text?: T;
  caption?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  imageType?: T;
  dimensions?:
    | T
    | {
        width?: T;
        height?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CustomButtonBlock".
 */
export interface CustomButtonBlock {
  buttonText?: string | null;
  buttonLink?: string | null;
  buttonStyle: 'primary' | 'secondary' | 'outline' | 'ghost';
  openInNewTab?: boolean | null;
  buttonSize?: ('small' | 'medium' | 'large') | null;
  alignment?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'customButton';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  content?: string | null;
  type: 'info' | 'warning' | 'success' | 'error';
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}